title: Avicus Documentation
description: > # this means to ignore newlines until "baseurl:"
  Your one stop shop for all info regarding all the modules used to create fun and exciting Atlas maps!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
